/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardsCardSlugRouteImport } from './routes/cards/$cardSlug'
import { Route as LearnCastingResolutionRouteImport } from './routes/learn/casting-resolution'
import { Route as LearnCombatRouteImport } from './routes/learn/combat'
import { Route as LearnCoreConceptsRouteImport } from './routes/learn/core-concepts'
import { Route as LearnTurnStructureRouteImport } from './routes/learn/turn-structure'
import { Route as MechanicsMechanicSlugRouteImport } from './routes/mechanics/$mechanicSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsCardSlugRoute = CardsCardSlugRouteImport.update({
  id: '/cards/$cardSlug',
  path: '/cards/$cardSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCastingResolutionRoute = LearnCastingResolutionRouteImport.update({
  id: '/learn/casting-resolution',
  path: '/learn/casting-resolution',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCombatRoute = LearnCombatRouteImport.update({
  id: '/learn/combat',
  path: '/learn/combat',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCoreConceptsRoute = LearnCoreConceptsRouteImport.update({
  id: '/learn/core-concepts',
  path: '/learn/core-concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTurnStructureRoute = LearnTurnStructureRouteImport.update({
  id: '/learn/turn-structure',
  path: '/learn/turn-structure',
  getParentRoute: () => rootRouteImport,
} as any)
const MechanicsMechanicSlugRoute = MechanicsMechanicSlugRouteImport.update({
  id: '/mechanics/$mechanicSlug',
  path: '/mechanics/$mechanicSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards/$cardSlug': typeof CardsCardSlugRoute
  '/learn/casting-resolution': typeof LearnCastingResolutionRoute
  '/learn/combat': typeof LearnCombatRoute
  '/learn/core-concepts': typeof LearnCoreConceptsRoute
  '/learn/turn-structure': typeof LearnTurnStructureRoute
  '/mechanics/$mechanicSlug': typeof MechanicsMechanicSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards/$cardSlug': typeof CardsCardSlugRoute
  '/learn/casting-resolution': typeof LearnCastingResolutionRoute
  '/learn/combat': typeof LearnCombatRoute
  '/learn/core-concepts': typeof LearnCoreConceptsRoute
  '/learn/turn-structure': typeof LearnTurnStructureRoute
  '/mechanics/$mechanicSlug': typeof MechanicsMechanicSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards/$cardSlug': typeof CardsCardSlugRoute
  '/learn/casting-resolution': typeof LearnCastingResolutionRoute
  '/learn/combat': typeof LearnCombatRoute
  '/learn/core-concepts': typeof LearnCoreConceptsRoute
  '/learn/turn-structure': typeof LearnTurnStructureRoute
  '/mechanics/$mechanicSlug': typeof MechanicsMechanicSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cards/$cardSlug'
    | '/learn/casting-resolution'
    | '/learn/combat'
    | '/learn/core-concepts'
    | '/learn/turn-structure'
    | '/mechanics/$mechanicSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cards/$cardSlug'
    | '/learn/casting-resolution'
    | '/learn/combat'
    | '/learn/core-concepts'
    | '/learn/turn-structure'
    | '/mechanics/$mechanicSlug'
  id:
    | '__root__'
    | '/'
    | '/cards/$cardSlug'
    | '/learn/casting-resolution'
    | '/learn/combat'
    | '/learn/core-concepts'
    | '/learn/turn-structure'
    | '/mechanics/$mechanicSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsCardSlugRoute: typeof CardsCardSlugRoute
  LearnCastingResolutionRoute: typeof LearnCastingResolutionRoute
  LearnCombatRoute: typeof LearnCombatRoute
  LearnCoreConceptsRoute: typeof LearnCoreConceptsRoute
  LearnTurnStructureRoute: typeof LearnTurnStructureRoute
  MechanicsMechanicSlugRoute: typeof MechanicsMechanicSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$cardSlug': {
      id: '/cards/$cardSlug'
      path: '/cards/$cardSlug'
      fullPath: '/cards/$cardSlug'
      preLoaderRoute: typeof CardsCardSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/casting-resolution': {
      id: '/learn/casting-resolution'
      path: '/learn/casting-resolution'
      fullPath: '/learn/casting-resolution'
      preLoaderRoute: typeof LearnCastingResolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/combat': {
      id: '/learn/combat'
      path: '/learn/combat'
      fullPath: '/learn/combat'
      preLoaderRoute: typeof LearnCombatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/core-concepts': {
      id: '/learn/core-concepts'
      path: '/learn/core-concepts'
      fullPath: '/learn/core-concepts'
      preLoaderRoute: typeof LearnCoreConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/turn-structure': {
      id: '/learn/turn-structure'
      path: '/learn/turn-structure'
      fullPath: '/learn/turn-structure'
      preLoaderRoute: typeof LearnTurnStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechanics/$mechanicSlug': {
      id: '/mechanics/$mechanicSlug'
      path: '/mechanics/$mechanicSlug'
      fullPath: '/mechanics/$mechanicSlug'
      preLoaderRoute: typeof MechanicsMechanicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsCardSlugRoute: CardsCardSlugRoute,
  LearnCastingResolutionRoute: LearnCastingResolutionRoute,
  LearnCombatRoute: LearnCombatRoute,
  LearnCoreConceptsRoute: LearnCoreConceptsRoute,
  LearnTurnStructureRoute: LearnTurnStructureRoute,
  MechanicsMechanicSlugRoute: MechanicsMechanicSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
